export const actionTypes = {
  LOAD_INITIAL_CONTACTS: 'LOAD_INITIAL_CONTACTS',
  LOAD_CONTACTS: 'LOAD_CONTACTS',
  SAVE_CONTACT: 'SAVE',
  REMOVE_CONTACT: 'REMOVE',

  SEARCH_CONTACT: 'SEARCH_CONTACT',
  CANCEL_SEARCH_CONTACT: 'CANCEL_SEARCH_CONTACT',

  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',

  SELECT_CONTACT: 'SELECT_CONTACT'
}